---
abstract: 'simple irc bot baseclass'
author:
  - 'Tom Insam <tom@jerakeen.org>'
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot
no_index:
  directory:
    - t
    - xt
    - utils
    - examples
requires:
  POE::Component::IRC: 6.55
  Text::Wrap: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Bot-BasicBot
  homepage: http://search.cpan.org/dist/Bot-BasicBot/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/bot-basicbot.git
version: 0.85
x_authority: cpan:HINRIK
