---
name: Bot-BasicBot
version: 0.61
author:
  - Tom Insam E<lt>tom@jerakeen.orgE<gt>
abstract: simple irc bot baseclass
license: perl
requires:
  POE: 0.22
  POE::Component::IRC: 2
  Test::More: 0.01
  Text::Wrap: 0
provides:
  Bot::BasicBot:
    file: lib/Bot/BasicBot.pm
    version: 0.61
generated_by: Module::Build version 0.261
